name: Auto Create Pull Request

on:
  push:
    branches:
      - master

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
      
      - name: Create Pull Request
        id: open-pr
        env:
          GITHUB_TOKEN: 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
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d '{"title":"Automatic PR from Master","body":"This PR was automatically created from the '\''master'\'' branch.","head":"master","base":"main"}' \
            "https://api.github.com/repos/${{ github.repository }}/pulls"
