name: Create PR on Push to Master

on:
  push:
    branches:
      - master

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_title: "Automatic PR from Master"
          pr_body: "This PR was automatically created from the 'master' branch."
